// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

//
type WorkbookFunctionsVdbRequestBuilder struct{ BaseRequestBuilder }

// Vdb action undocumented
func (b *WorkbookFunctionsRequestBuilder) Vdb(reqObj *WorkbookFunctionsVdbRequestParameter) *WorkbookFunctionsVdbRequestBuilder {
	bb := &WorkbookFunctionsVdbRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/vdb"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type WorkbookFunctionsVdbRequest struct{ BaseRequest }

//
func (b *WorkbookFunctionsVdbRequestBuilder) Request() *WorkbookFunctionsVdbRequest {
	return &WorkbookFunctionsVdbRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject,
			tenantID: b.tenantID, applicationID: b.applicationID, clientSecurityKey: b.clientSecurityKey},
	}
}

//
func (r *WorkbookFunctionsVdbRequest) Post(ctx context.Context) (resObj *WorkbookFunctionResult, err error) {
	err = r.JSONRequest(ctx, "POST", "", r.requestObject, &resObj)
	return
}
