// Code generated by msgraph.go/gen DO NOT EDIT.

package msgraph

import "context"

//
type WorkbookFunctionsCoshRequestBuilder struct{ BaseRequestBuilder }

// Cosh action undocumented
func (b *WorkbookFunctionsRequestBuilder) Cosh(reqObj *WorkbookFunctionsCoshRequestParameter) *WorkbookFunctionsCoshRequestBuilder {
	bb := &WorkbookFunctionsCoshRequestBuilder{BaseRequestBuilder: b.BaseRequestBuilder}
	bb.BaseRequestBuilder.baseURL += "/cosh"
	bb.BaseRequestBuilder.requestObject = reqObj
	return bb
}

//
type WorkbookFunctionsCoshRequest struct{ BaseRequest }

//
func (b *WorkbookFunctionsCoshRequestBuilder) Request() *WorkbookFunctionsCoshRequest {
	return &WorkbookFunctionsCoshRequest{
		BaseRequest: BaseRequest{baseURL: b.baseURL, client: b.client, requestObject: b.requestObject,
			tenantID: b.tenantID, applicationID: b.applicationID, clientSecurityKey: b.clientSecurityKey},
	}
}

//
func (r *WorkbookFunctionsCoshRequest) Post(ctx context.Context) (resObj *WorkbookFunctionResult, err error) {
	err = r.JSONRequest(ctx, "POST", "", r.requestObject, &resObj)
	return
}
